### ISSUE TITLE
[Chrome and IExplorer libs] 'Abort' does not exist in the current context 

### ISSUE THREAD

**Issue by longdinhpmt** [Rigel-Technologies/RPA-Suite-Csharp-Library#19]
I have problems with the Chrome and IExplorer libs, after pulling your source code, I make a build for the solution, then I got this issue as below image.
![image](https://user-images.githubusercontent.com/82428861/129299893-f2ebec47-ef6d-4ee0-8ade-e57326b85682.png)

Please take a look at it and push your fixs.

Thanks and Best Regards,

**Comment by longdinhpmt** [comment]
As I understand I need to add one variable like that:

`private int Abort = 0;`

Please correct me if I'm wrong.

**Comment by destrebo** [comment]
Thanks @longdinhpmt. We have fixed the bug.
You didn't need to add any variables. The Chrome library and IExplore have code in Cartes Script and were left out of an update. It was enough to declare a property public in MyCartesProcess.

All the best
